### ISSUE TITLE
Keep user logged in / Set user from Cookie

### ISSUE THREAD

**Issue by luminous8** [Atinux/nuxt-auth-utils#102]
When I close my browser, the session is not stored anymore, so I'm storing the authToken in a dedicated cookie.

My understanding was that `sessionHooks.hook('fetch')` would be fired when the app is rendered, and it would read the cookie and set the user with `setUserSession`.

But it seems that this hook is fired only when there's already a session set, not when there's no session set.

My question is: **What's the proper way to set up a session from a stored cookie?**

_I'm pretty sure I'm doing something wrong but no idea what_

Thanks!

**Comment by Atinux** [comment]
Hi @luminous8 

Could you set the options to update the cookie expiration?

https://github.com/Atinux/nuxt-auth-utils?tab=readme-ov-file#configuration

```ts
export default defineNuxtConfig({
   modules: ['nuxt-auth-utils'],
  runtimeConfig: {
    session: {
      maxAge: 60 * 60 * 24 * 7 // 1 week
    }
  }
})
```

This way the cookie won't expire at the session (browser close) but after a 7 days if not updated (using `setUserSession(event, ...)`

**Comment by luminous8** [comment]
Thanks! I realize that I over-engineered something when the solution was already built-in (:

Thanks for this module and all the updates you've made recently

**Comment by luminous8** [comment]
Thanks! I realize that I over-engineered something when the solution was already built-in (:

Thanks for this module and all the updates you've made recently
