### ISSUE TITLE
yarn upgrade-interactive is not showing the new release version as latest

### ISSUE THREAD

**Issue by mendrinos** [Atinux/nuxt-auth-utils#116]
<img width="949" alt="Screenshot 2024-07-08 at 10 28 36 AM" src="https://github.com/Atinux/nuxt-auth-utils/assets/1592441/a360462b-9ddb-48be-b641-f7540d237a99">

**Comment by mendrinos** [comment]
YN0000: · Yarn 4.3.1
➤ YN0000: ┌ Resolution step
➤ YN0082: │ nuxt-auth-utils@npm:^0.2.0: No candidates found
➤ YN0000: └ Completed in 1s 272ms
➤ YN0000: · Failed with errors in 1s 280ms

**Comment by Barbapapazes** [comment]
As I can see on npm, the 0.2.0 is only available since a day (despite the release on GitHub 5 days ago). Maybe Atinux forgot to publish the version 🤷‍♂️

But appart that, everything is ok and it should works now the package is published.
