### ISSUE TITLE
Pop Up Window

### ISSUE THREAD

**Issue by gcom-ryan** [Atinux/nuxt-auth-utils#125]
Does anyone know a way to get this to work with a pop-up window like we so on most websites?

I have this working inside the parent window, and the whole page refreshes. That is OK, but that is not how most websites using OAuth work.

Any ideas?

**Comment by Atinux** [comment]
One solution I can see is the ability to watch the auth state in the LocalStorage to make it reactive on other tabs.

**Comment by gcom-ryan** [comment]
We can try this. We also cannot refresh any pages in the app or we get logged out. Could this be due to the same reason?
