### ISSUE TITLE
ability to specify redirect_uri for google and github - allows compatibility with CloudFront+Lambda

### ISSUE THREAD

**Issue by acidjazz** [atinux/nuxt-auth-utils#137]
It would be nice to be able to specify the `redirect_uri` - I have a production setup on AWS Lambda+Cloudfront deployed via [fume](https://fume.app)

 - in the Google dev console  i have https://domain/api/oauth/google
 - when i get the 400: redirect_uri_mismatch, google doesn't see cloudfront, so [this line here](https://github.com/atinux/nuxt-auth-utils/blob/0345169251c9c7d45a436090f2647bf8b7df1b96/src/runtime/server/lib/oauth/google.ts#L84) actually sees `https://mkniuoyitj.execute-api.us-east-1.amazonaws.com/api/oauth/google` - which while is possibly fixable - this would definitely change on a per-environment basis.

<img width="590" alt="image" src="https://github.com/user-attachments/assets/f6e59bcd-0063-41d6-953e-ae1c308bc1bc">

I will work on a PR as soon as i find time

**Comment by acidjazz** [comment]
Even when adding the gateway URL behind the lambda, its not pretty

<img width="555" alt="image" src="https://github.com/user-attachments/assets/c1c372d6-6129-46c1-b003-efb3f1577e67">

**Comment by acidjazz** [comment]
I can confirm GitHub needs this as well for AWS Lambda

**Comment by atinux** [comment]
Solution is similar to https://github.com/atinux/nuxt-auth-utils/issues/94#issuecomment-2258056489
