### ISSUE TITLE
How to set maxAge to cookie?

### ISSUE THREAD

**Issue by Serpentarius13** [atinux/nuxt-auth-utils#139]
There is no such option as of now in config settings, only sameSite under cookie

**Comment by Barbapapazes** [comment]
Hey,

Do you try this? https://github.com/atinux/nuxt-auth-utils#configuration

**Comment by Serpentarius13** [comment]
> Hey,
> 
> Do you try this? https://github.com/atinux/nuxt-auth-utils#configuration

Yes. But the type only allows sameSite property on cookie

**Comment by atinux** [comment]
You need to use the `session` config:

```ts
export default defineNuxtConfig({
  modules: ['nuxt-auth-utils'],
  runtimeConfig: {
    session: {
      maxAge: 60 * 60 * 24 * 7 // 1 week
    }
  }
})
```

It will forward it to the cookie.

**Comment by Barbapapazes** [comment]
Because it's generated on the fly


https://github.com/user-attachments/assets/df43f3b8-96e5-4ed6-98cd-7f11ba917069

**Comment by Serpentarius13** [comment]
> Because it's generated on the fly
> 
>  Screen.Recording.2024-08-29.at.14.42.06.mov 
> And the defaults are the following
> 
> ![Screenshot 2024-08-29 at 14 43 31](https://private-user-images.githubusercontent.com/45267552/362689694-532c8892-e5f9-4490-aa8a-ac9dc7a2e625.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5ODI2MTAsIm5iZiI6MTcyNDk4MjMxMCwicGF0aCI6Ii80NTI2NzU1Mi8zNjI2ODk2OTQtNTMyYzg4OTItZTVmOS00NDkwLWFhOGEtYWM5ZGM3YTJlNjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDAxNDUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkOGYzNzMxMWFmMjUzM2U1YWFiZGYwZTEzOThkYTk2NWY0YTgzYmRmOGNkY2UyYmI1NTM3Nzc5YzBjYTQxYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wrkh4lXeYLQJU3Lp8maiCBjDqsnM1lJHORT2MMiNEX0)
> 
> so the generated `runtimeConfig` only have keys `name`, `password` and `sameSite`.

Wouldn't it be sane to generate the type for maxAge? What's the problem here?
