### ISSUE TITLE
Simplify OAuth Handler

### ISSUE THREAD

**Issue by Barbapapazes** [atinux/nuxt-auth-utils#148]
Hello,

There is a lot of code redundancy within OAuthHandler and I think there is a lot of possible refactor to simplify the code and to help maintenance.

I will make multiple PR to try to resolve this:

- #145
- #146 
- #147

**Comment by atinux** [comment]
Shall we close?

**Comment by Barbapapazes** [comment]
I'll see.

But if I remember well, there is still a possible simplification.
