### ISSUE TITLE
Add `hashPassword()` and `verifyPassword()` server utils

### ISSUE THREAD

**Issue by atinux** [atinux/nuxt-auth-utils#155]
```ts
// import is optional
import { hashPassword, verifyPassword } from '#auth-utils'

const hash = hashPassword('user_password')
// $2a$10$vEdoE9pqBlkJMqWmbk1JWuEYbJoansodgPo7a2GBkXsO8SleGXCr6

if (verifyPassword(existingHash, plainTextValue)) {
  // password is correct
}
```

Demo from bcrypt-edge on https://github.com/atinux/nuxt-bcrypt-edge

The second argument of `hashPassword` is the same as [hashSync](https://github.com/bruceharrison1984/bcrypt-edge/blob/e1b41aa46c221ed5b92a59541701add6bdbfc49d/src/bcrypt-edge.ts#L38)

```ts
const hash = hashPassword('use_password', 12)
```

**Comment by mdforiduddin** [comment]
fix(auth): hashPassword and verifyPassword not defined from nuxt-auth-utils

Tried to use `hashPassword` and `verifyPassword` as per nuxt-auth-utils documentation, but encountered "not defined" error.

- Added proper `auth` config in `nuxt.config.ts`
- Confirmed `nuxt-auth-utils` is installed correctly

My Nuxt Config File Code 

`export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true },
  modules: ['nuxt-auth-utils'],
  auth: {
    hash: {
      scrypt: {
        cost: 16384, blockSize: 8, parallelization: 1, saltSize: 16, maxMemory: 33554432, keyLength: 64
      }
    }
  },
})`

**Comment by mdforiduddin** [comment]
hashPassword and verifyPassword not defined from nuxt-auth-utils

Tried to use `hashPassword` and `verifyPassword` as per nuxt-auth-utils documentation, but still getting "not defined" error.

✔ Added proper auth config in nuxt.config.ts  
✔ Confirmed nuxt-auth-utils is installed correctly

nuxt.config.ts:
```
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true },
  modules: ['nuxt-auth-utils'],
  auth: {
    hash: {
      scrypt: {
        cost: 16384, blockSize: 8, parallelization: 1, saltSize: 16, maxMemory: 33554432, keyLength: 64
      }
    }
  },
})
```
