### ISSUE TITLE
setUserSession specify max age

### ISSUE THREAD

**Issue by jaketig** [atinux/nuxt-auth-utils#169]
Is there any way to pass maxAge when calling setUserSession instead of globally in nuxt.config?

My login endpoint validates user credentails against a pre-existing internal only SSO service.
That service is returning the same token/expiration if a user logs in more than once 
I store that token in my user data with setUserSession and use it to call other services server side later on.
I would like to be able to match the expiration of the session with the token expiration.

**Comment by atinux** [comment]
It's now possible with `v0.3.8`:

```ts
await setUserSession(event, { ... } , {
  maxAge: 60 * 60 * 24 * 7 // 1 week
})
```
