### ISSUE TITLE
How safe is putting user password in user object

### ISSUE THREAD

**Issue by CorrM** [atinux/nuxt-auth-utils#174]
How safe is putting user password in user object.
Is there a validation happens when call `getUserSession`? so if client-side changed it will fail?
What is the purpose of `NUXT_SESSION_PASSWORD`? validate client data when reach the server?
Why in the example `password` is saved in the session?
https://github.com/atinux/nuxt-auth-utils/blob/23ccd4c1ea62043ec2f25d7bf61d1e57389b7dbb/playground/server/api/login.post.ts#L10-L15

**Comment by atinux** [comment]
Never put your user password in the session, I has to hashed and put in database and never sent back.

rhe NUXT_SESSION_PASSWORD is used for encrypting the cookie and has nothing to do with your user credentials.

**Comment by CorrM** [comment]
what about validation? i can trust that cookie data? i mean in the same way JWT work?

**Comment by anuragkumar19** [comment]
@CorrM Session cookies are encrypted using your `NUXT_SESSION_PASSWORD` and client cannot see, change the data or create another without the `NUXT_SESSION_PASSWORD`. It works like JWT , the difference is JWT are not encrypted any one can view the data while but sealed session cookie are encrypted.

Is is based on IronSession's implementation which is inspired by Ruby on Rails. You can read more about it.

https://github.com/vvo/iron-session

https://guides.rubyonrails.org/security.html#session-storage

**Comment by anuragkumar19** [comment]
@CorrM Yes, you can trust cookie data. Cookie session are encrypted using `NUXT_SESSION_PASSWORD`  so any one cannot view, edit or create the token without `NUXT_SESSION_PASSWORD`. It works like JWTs but difference is JWTs are not encrypted so anyone can view the data stored inside JWTs.

**Comment by CorrM** [comment]
Thanks, guys all my questions are answered.

_maybe add that into FAQ section or something like that would be nice_
