### ISSUE TITLE
steam does not require Validate OpenID Authentication

### ISSUE THREAD

**Issue by mavrick** [atinux/nuxt-auth-utils#177]
looking over the code for passport-steam they simply check if the openid.op_endpoint matches config.authorizationURL

```javascript
if (query['openid.op_endpoint'] !== config.authorizationURL) {
  const error = createError({
    statusCode: 401,
    message: 'Claimed identity is invalid.',
  });
  if (!onError) throw error;
  return onError(event, error);
}
 ```
 
 trying to run this in production with a https:// endpoint the call to `https://steamcommunity.com/openid/login` fails with 403

**Comment by atinux** [comment]
Pull request welcome if you find a way to improve the Steam support
