### ISSUE TITLE
Rename `secure` to `private`

### ISSUE THREAD

**Issue by tobiasdiez** [atinux/nuxt-auth-utils#201]
Currently, there is a field `secure: SecureSessionData` in the session data. If my understanding of the situation is correct, I think this is a huge misnomer. `secure` implies I can store there whatever sensitive data I would like to associate with the current session (say api keys or permissions). However, currently this data is still send to the user in the cookie, right? The only difference with the rest of the data in the session is that one cannot easily receive the data from the public api `fetch` endpoint. However, an attacker still has access to the data in encrypted form - he only needs to "guess" (or finds out by other means) of the password used to encrypt it, and thereby gets access to all the `secure` data.

For this reason, I believe `private` better conveys the intention of this kind of data: put things here that you don't want to have public to the user (eg an internal userid) but which is not super security relevant. All really sensitive data should be stored and only be fetched on the server.

**Comment by atinux** [comment]
We cannot use the name `private` as it is a reserved work in JS, so you cannot do:

```ts
// will not work
const { private } = await getUserSession(event)
```

This is why I named it `secure`.

> he only needs to "guess" (or finds out by other means) of the password used to encrypt it, and thereby gets access to all the secure data.

As the minimum length is 32 chars for the session password, it will take centuries to guess it.

**Comment by atinux** [comment]
In that case I would suggest to store only the ID of a session and then use a storage (see https://nitro.unjs.io/guide/storage) to keep the value of the session in a server storage.

**Comment by tobiasdiez** [comment]
> In that case I would suggest to store only the ID of a session and then use a storage (see https://nitro.unjs.io/guide/storage) to keep the value of the session in a server storage.

That's what I'm doing. I just thought the default auth-module for nuxt should recommend very strong security norms. My fear was that people just take "secure" at face value and store sensitive information in there. Not everyone looks at the code to see where exactly this secure information is living and that it is send to the user.

Perhaps, add at least a remark to the documentation?
