### ISSUE TITLE
salt must be a Buffer

### ISSUE THREAD

**Issue by michaelsieminski** [atinux/nuxt-auth-utils#207]
Hey, after updating to the latest nuxt auth utils and implementing the new Password Hashing & Verifying I am receiving the error "salt must be a buffer" in Cloudflare.

**Comment by atinux** [comment]
What is your compatibility flags on Cloudflare @michaelsieminski 

Make sure to set `nodejs_compat` and a compatibility date at least in October

**Comment by michaelsieminski** [comment]
> What is your compatibility flags on Cloudflare @michaelsieminski
> 
> Make sure to set `nodejs_compat` and a compatibility date at least in October

I have the compatibility flag nodejs_compat already set and the date to Sep. 2024

**Comment by atinux** [comment]
Try to set the compat flag to `nodejs_compat_v2` then

**Comment by michaelsieminski** [comment]
> Try to set the compat flag to `nodejs_compat_v2` then

didn't seem to help :/

**Comment by atinux** [comment]
do you have a reproduction?

**Comment by tahirmahmudzade** [comment]
> Try to set the compat flag to `nodejs_compat_v2` then

i had the same issue but this completely solved the issue for me
