### ISSUE TITLE
Add option for additional query parameters

### ISSUE THREAD

**Issue by cosbgn** [Atinux/nuxt-auth-utils#22]
Would be great if the config would have a key like `authorization_params` where we can add any optional parameter the provider expects.

In my example I would like to add `?access_type=offline` to the `authorizationURL` for Google (So that it returns also the refresh token). Having one general `authorization_params` object would avoid having to add different parameters for each provider manually. 

Ideally I would have something like:

```js
export default oauth.googleEventHandler({
	config:{
		authorization_params: {  // Something like this would work perfectly
		    access_type:"offline"
		},
		scope: [
			'https://www.googleapis.com/auth/userinfo.email',
			'https://www.googleapis.com/auth/tasks.readonly' // This is great!
		]
	},
	async onSuccess(event, { user, tokens }) {
		console.log(tokens.refresh_token) // Save this in DB
		await setUserSession(event, { user, loggedInAt: Date.now() })
	  	return sendRedirect(event, '/')
	}
})

```

From my understanding this is currently impossible, right?

**Comment by Atinux** [comment]
We could add a `authorizationQuery` object  that could be merged in https://github.com/Atinux/nuxt-auth-utils/blob/c60fde74c1b59311b7eb68b861d459f1a7777814/src/runtime/server/lib/oauth/google.ts#L83-L88

```ts
return sendRedirect(
  event,
  withQuery(config.authorizationURL as string, {
    ...config.authorizationQuery,
    response_type: 'code',
    client_id: config.clientId,
    redirect_uri: redirectUrl,
    scope: config.scope.join(' '),
  })
)
```

**Comment by cosbgn** [comment]
Yes that would be great. This way I could simply make `authorizationQuery = getQuery(event)` and edit the flow depending on the situation. 

BTW this module is amazing, so easy to use. I've been fighting with auth.js/nextjs for a year now and I'm amazing how easy this is. 

I hope it becomes the official nuxt/auth library soon! It's perfect.

**Comment by Atinux** [comment]
Re-opening since it has not been implemented!

Thanks for the kind words 😊
