### ISSUE TITLE
Unable to use `hashPassword` in Prisma seed files

### ISSUE THREAD

**Issue by iLucasPires** [atinux/nuxt-auth-utils#246]
Hi, I'm trying to use the `hashPassword` function from the `nuxt-auth-utils` package to hash passwords in a Prisma seed file. However, I'm unable to import or use the function correctly within my seeding logic.

  
### Example Code (Prisma seed file):
```javascript
import { PrismaClient } from '@prisma/client';
import { hashPassword } from 'nuxt-auth-utils'; // Fails here

const prisma = new PrismaClient();

async function main() {
  const hashedPassword = await hashPassword('user_password');

  await prisma.user.create({
    data: {
      email: 'user@example.com',
      password: hashedPassword,
    },
  });
}

main()
  .catch(e => console.error(e))
  .finally(async () => {
    await prisma.$disconnect();
  });
```

I would appreciate any help or guidance on resolving this issue.

Thanks!

**Comment by atinux** [comment]
Hi @iLucasPires 

I recommend you to use server tasks for seed, see https://nitro.unjs.io/guide/tasks

See example: https://hub.nuxt.com/docs/recipes/drizzle#seed-the-database-optional

**Comment by iLucasPires** [comment]
I understand, Vlw vlw(Brazilian slang for thank you)
