### ISSUE TITLE
How to redirect a signed-in user during app startup?

### ISSUE THREAD

**Issue by julianfox** [atinux/nuxt-auth-utils#248]
Hello,
I'm having trouble figuring out how to redirect signed-in users right when the app starts.

My first attempt was to add middleware to my landing page ("/"):
```
export default defineNuxtRouteMiddleware((to, from) => {
  const { loggedIn } = useUserSession()

  if (loggedIn.value) {
    return navigateTo(`/cards`)
  }
})
```

This works perfectly in my local environment, but in production, the redirection doesn't happen, even though /api/_auth/session returns a 200 status.

I then tried a different approach:
```
export default defineNuxtRouteMiddleware(async (to, from) => {
  const { loggedIn, fetch } = useUserSession()

  await fetch()

  if (loggedIn.value) {
    return navigateTo(`/cards`)
  }
})
```

This works, but there's a 2-3 second delay before the user is redirected. The landing page is rendered first, and then the user is redirected a few seconds later. It's better, but not ideal.

I also have a plugin that hooks into fetch on the server:
```
export default defineNitroPlugin(() => {
  sessionHooks.hook('fetch', async (session, event) => {
    const user = session.user

    if (!user) {
      return
    }

    const userDoc = await UserSchema.findOne({ _id: user._id }, 'premium').lean()

    if (!userDoc) {
      return
    }

    session.user.premium = userDoc.premium

    return session
  })
})
```

However, even when I remove this plugin, the problem persists.

Is there another solution to handle this more smoothly? Am I doing something wrong?

**Comment by atinux** [comment]
It works perfectly when tested both locally & in production, see https://github.com/Atinux/nuxt-auth-utils/blob/main/playground/pages/secret.vue

how do you deploy your project in production? Do you have SSR disabled?

**Comment by julianfox** [comment]
Thanks @atinux,
I think I've found the issue:
```
routeRules: {
    '/': { prerender: true },
  },
```

I will test, but if I understand it right, prerender by definition do not use SSR?

**Comment by julianfox** [comment]
Problem fixed; it was indeed due to my route rules configuration.

**Comment by kleinpetr** [comment]
Hi @atinux I am currently facing exactly same issue 🤔  I have disabled all `routeRules` using NuxtHub for deployment. 
The session is resolved well during ssr only locally. In the production it is resolved after hydration with some delay.

Should I open new issue or re-open this one?

**Comment by atinux** [comment]
Do you have any cache setup on your app @kleinpetr ?

**Comment by kleinpetr** [comment]
@atinux not in the code explicitly, so it means I don't use any cached handlers, etc.

**Comment by DavidSabine** [comment]
> how do you deploy your project in production? Do you have SSR disabled?

Can someone please explain whether SSR **should** or *should not** be disabled?

I've set `ssr: true,` because the OgImage complains. But I thought it was Nuxt's default to render server side.

**Comment by kleinpetr** [comment]
@atinux I've realized that sometimes when I have exists session and access `/api/_auth/session` there is only `session` object and when I hit reload on this api route it extends by `user` object, so then I can continue to my app to get logged in. I am not sure what is the concept idea behind `session` and `user` and `loggedIn` helper, but in my case I have

`session` - I create after each login which contains expiration, ip, device info (by this I can manage logged devices)
`user` - it's user data object, with all necessary personal infomration such as name, avatar, ...

As I mentioned, I've registered a server plugin to extend a user session by `data` object 
```ts
// server/plugins/session.ts
export default defineNitroPlugin(() => {
  // Called when the session is fetched during SSR for the Vue composable (/api/_auth/session)
  // Or when we call useUserSession().fetch()
  sessionHooks.hook('fetch', async (session, event) => {
    if (!session.data) return

    const authSession = await useDrizzle().query.sessions.findFirst({
      where: eq(tables.sessions.id, session.data.id),
    })

    if (!authSession) {
      // todo: sentry?
      console.error('Session not found')
      clearUserSession(event)
      return sendRedirect(event, '/')
    }

    const user = await useDrizzle().query.users.findFirst({
      where: eq(tables.users.id, session.data.userId),
    })

    if (!user) {
      // todo: sentry
      console.error('User not found')
      clearUserSession(event)
      return sendRedirect(event, '/')
    }

    // console.log('Session fetched set user session:', user)
    await setUserSession(event, {
      user,
    })
  })

  // Called when we call useUserSession().clear() or clearUserSession(event)
  sessionHooks.hook('clear', async session => {
    if (!session.data) return

    // Clear the session data
    await useDrizzle().delete(tables.sessions)
      .where(eq(tables.sessions.id, session.data.id))
  })
})
```

so in that case I've set auth types like this
```ts
//auth.d.ts
declare module '#auth-utils' {

  interface User extends AuthUser {

  }

  interface UserSession {
    user: User | null
    data?: AuthSession
  }

  // interface SecureSessionData {
  // Add your own fields
  // }
}
```

**Comment by luminous8** [comment]
@julianfox did you found a solution to redirect signed-in user on a prerendered route?
