### ISSUE TITLE
Include All JWT Properties in OAuth onSuccess Data

### ISSUE THREAD

**Issue by kbarnesMCC** [atinux/nuxt-auth-utils#270]
Currently the `onSuccess()` handler for OAuth support exposes `user` and `tokens` attributes; where the details under `user` are a subset of the JWT decoded details from `tokens.id_token`.

Wondering if it would be possible to instead allow consumers to obtain ALL JWT decoded properties from `tokens.id_tokens`?

This would allow consumers to avoid a secondary call to decode the JWT to obtain things like `sid` (which are used for RP-initiated logout requests for some providers).

**Comment by atinux** [comment]
What OAuth provider are you using exactly?

**Comment by kbarnesMCC** [comment]
I see, interesting; so you don't decode/validate the JWT in any capacity you're just passing it through.

Ok, well consider this one closed; I misunderstood what was happening under the hood!
