### ISSUE TITLE
Navigation to provider route SSR issue

### ISSUE THREAD

**Issue by angelhdzmultimedia** [Atinux/nuxt-auth-utils#28]
Hello Nuxters/Vuetists 🔥💚,

I was playing for hours to solve my issue. 
If I use `useFetch('/api/auth/github', {redirect: 'follow'})`, I get error:
```
(redirected from 'http://localhost:3000/api/auth/github') from origin 'http://localhost:3000' has been blocked by CORS policy: No 'vi-tr.js:1 
        
        
       GET https://github.com/login/oauth/authorize?client_id=*****&redirect_uri=http://localhost:3000/api/auth/github&scope=user:email net::ERR_FAILED 302 (Found)
login:1 Access to fetch at 'https://github.com/login/oauth/authorize?client_id=*****&redirect_uri=http://localhost:3000/api/auth/github&scope=user:email' (redirected from 'http://localhost:3000/api/auth/github') from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled..
```

Then if I use `navigateTo('/api/auth/github')`:

![image](https://github.com/Atinux/nuxt-auth-utils/assets/10191085/d1bcf553-a3a2-4ccb-8ebe-72751b77ec96)

And when I refresh the page with url `http://localhost:3000/api/auth/github`, then it redirects to Github login page.

**So my only options are:** 

1.  `navigateTo('/api/auth/github', {open: {target: '_self'}})`:
2. `window.location.href = '/api/auth/github'`

Wanna read your thoughts. 👋

**Comment by Atinux** [comment]
Hey @angelhdzmultimedia 

You need to let the user go this route using the browser directly, so your two options are good.

As well as using a normal `<a>` or `<NuxtLink to="/api/auth/github" external">`
