### ISSUE TITLE
Warn: circular dependency: virtual:#imports

### ISSUE THREAD

**Issue by dvogelg4al** [atinux/nuxt-auth-utils#292]
Suddenly got this warning I hadn't seen before updating from 0.5.0 to 0.5.5. 

![image](https://github.com/user-attachments/assets/1e646f54-d0d1-42cb-b1d4-d4ee981daa88)

I only use google login and a custom apple flow based on a very simplified version of the one I had seen around here but these warnings are repeated for each provider. Would appreciate some advice. 

`    "nuxt": "^3.14.1592",
    "nuxt-auth-utils": "^0.5.5",
    "vue": "3.5.13",`

**Comment by atinux** [comment]
Do you have these warning with `npx nuxt dev` or `npx nuxt build`? I cannot reproduce it

**Comment by dvogelg4al** [comment]
Sorry @atinux I was on paternal leave for a while. These errors are still popping up and now we also get the following error (possibly a separate issue):
"WARN  [nuxt] Your project has pages but the <NuxtPage /> component has not been used. You might be using the <RouterView /> component instead, which will not work correctly in Nuxt. You can set pages: false in nuxt.config if you do not wish to use the Nuxt vue-router integration."

The warnings do not appear with npx nuxt dev or npx nuxt build. Is there a reason behind it?
