### ISSUE TITLE
Cannot augment `user` in UserSession

### ISSUE THREAD

**Issue by kingyue737** [Atinux/nuxt-auth-utils#31]
The playground project tries to augment `UserSession`:
https://github.com/Atinux/nuxt-auth-utils/blob/e344c9880491346ab73165ac4439c129b13ec15d/playground/auth.d.ts#L3

But `user` is already declared here:

https://github.com/Atinux/nuxt-auth-utils/blob/e344c9880491346ab73165ac4439c129b13ec15d/src/runtime/types/session.ts#L2

🤔I don't think it is possible to augment an already declared field of an interface.

Type errors in playground:
![image](https://github.com/Atinux/nuxt-auth-utils/assets/40021217/4ec171cd-9ad4-442f-8082-9e99a6b1a29a)

**Comment by Gerbuuun** [comment]
I am getting this TypeError in my project as well. I've been ignoring them for a while now as I haven't found a solution to this yet sadly...

It seems as if the `UserSession` type is 'stuck'.
Even the `requireUserSession` function return-type is not what I expect.
```ts
export async function requireUserSession(event: H3Event) {
  const userSession = await getUserSession(event)

  if (!userSession.user) {
    throw createError({
      statusCode: 401,
      message: 'Unauthorized'
    })
  }

  return userSession
}
```
It throws an error when `user` is falsy (this includes `undefined`). So when it ___does___ return it should be defined right?
Nope... the type is still `user: {} | undefined`

**Comment by kingyue737** [comment]
I manually remove the `user?: {}` from `node_modules/nuxt-auth-utils/dist/runtime/types/session.d.ts` via `pnpm patch`
