### ISSUE TITLE
Strange issue, Auth0 always needs to be logged in twice repeatedly to be recognized properly

### ISSUE THREAD

**Issue by BingZi-233** [Atinux/nuxt-auth-utils#33]
## Problem Description

I'm using this module for Auth widgets, but I'm currently having a problem that the data is not updated in time. Here are a few examples:

1. It always takes two logins to be released properly
2. When exiting, a route protection is always triggered to show normal

## devDependencies
```json
"devDependencies": {
    "@hypernym/nuxt-anime": "^2.1.1",
    "@nuxt/devtools": "latest",
    "@nuxtjs/color-mode": "^3.3.2",
    "@nuxtjs/tailwindcss": "^6.10.1",
    "nuxt": "^3.9.0",
    "nuxt-auth-utils": "^0.0.13",
    "vue": "^3.3.12",
    "vue-router": "^4.2.5"
  }
```

## Additional questions. 
In `node .output/server/index.mjs`, you can never log in successfully

**Comment by BingZi-233** [comment]
It was found that the cookie was not written after the first login

**Comment by BingZi-233** [comment]
To update the latest findings, only the sub field was obtained

**Comment by Atinux** [comment]
Do we need a fix for this?

**Comment by BingZi-233** [comment]
I've had this issue after switching multiple OAuth 2.0 vendors, and I'm not sure what went wrong
