### ISSUE TITLE
Utils does not work with Azure SWA

### ISSUE THREAD

**Issue by gps-lasrol** [Atinux/nuxt-auth-utils#43]
We are trying to use this with Azure Static Web App, but the redirect url is wrong.

From what i can see it gets the redirectUrl from `getRequestUrl(event).href`, this does not work with SWA since the hostname refers to an internal url for the function app.

You can see an example output here:
https://ambitious-dune-01c6e3503-preview.westeurope.4.azurestaticapps.net/api/info

Not sure what the best approach for this would be. X-Forward-For header contains only IP Adresse (i assume this is internal infrastructure at Microsoft). SWA does have a special header called 'x-ms-original-url' that contains the original url, it seems very specific for SWA and would only apply to apps running in Azure SWA. 

One possible solution would be to allow a configured redirectUrl (but its not the best solution IMO, in case we have multiple domains pointing to the same instance), another would be to create a custom handler for apps running in SWA.

Any suggestions on the best way to handle this?

**Comment by pi0** [comment]
Thanks for reporting detailed issue. it is unfortouante situation with azure. I have made an upstream issue if we can polyfill it for deployments: https://github.com/unjs/nitro/issues/2137

I think Nuxt and Nitro could also provide canonical URL support greatly for similar situations also: https://github.com/unjs/nitro/issues/2052


In the meantime, you can try to polyfill yourself like this (note: I haven't tested this code only to give some ideas): https://stackblitz.com/edit/nuxt-starter-wh1bwj?file=server%2Fplugins%2Fazure.ts

**Comment by PGLongo** [comment]
@gps-lasrol Have you attempted the fix suggested by @pi0?

I'm encountering the following error:

`{
  "code": 400,
  "message": "Login not supported for provider azureStaticWebApps"
}
`

**Comment by gps-lasrol** [comment]
@PGLongo i have not attempte the fix suggested yet, we are currently hosting our solution with docker and azure container apps as a workaround. We are going to try this fix, but i am not sure when we will be able to do it.

**Comment by PGLongo** [comment]
@pi0 & @Atinux, what are your thoughts on introducing an environment variable named NUXT_OAUTH_MICROSOFT_REDIRECT_URL?

IF NUXT_OAUTH_MICROSOFT_REDIRECT_URL is null, we could use `const redirectUrl = getRequestURL(event).href`. If not, we would use the specified value.

**Comment by PGLongo** [comment]
@gps-lasrol,  I can confirm that modifying the redirectUrl resolves the issue. Unfortunately, the fix suggested by @pi0  didn't work, so I've temporarily created a new provider that reads the redirectUrl from the .ENV file.

**Comment by Atinux** [comment]
I am fine adding `NUXT_OAUTH_MICROSOFT_REDIRECT_URL` env variable, happy to open a PR @PGLongo ?

**Comment by PGLongo** [comment]
> I am fine adding `NUXT_OAUTH_MICROSOFT_REDIRECT_URL` env variable, happy to open a PR @PGLongo ?

Sure! I will work on it during the WE.
