### ISSUE TITLE
(discord oauth2) Session state not persisting across page refreshes with Nuxt 3 and useUserSession only when deployed on Vercel

### ISSUE THREAD

**Issue by Inerska** [Atinux/nuxt-auth-utils#60]
Hello !

The project's working in local development, it's only messing up when deployed on Vercel : 
https://talent-hub.fr

You can even try it on in the website.

The redirect_uri is set, client_id / secret as well, everything is working, you can connect with Discord, but after the redirection, nothing seems persisted :  
`const {loggedIn, user, session, clear, logout} = useUserSession()`

The loggedIn is not set and the navbar is like for an authenticated user.

However, there's a page secured by an auth middleware  : 
pages/Profile.vue : 
```vue
<template>
</template>
<script lang="ts" setup>
definePageMeta({
    middleware: 'auth'
})
</script>
```

With the middleware : 
```ts
export default defineNuxtRouteMiddleware(() => {
    const { loggedIn } = useUserSession()

    if (!loggedIn.value) {
        return navigateTo('/')
    }
})
```

When navigating, you can access it, and when you refresh, you could see that's the navbar is working as expected.

But once you comeback to the home page, and refresh, everything disappear, and when coming back again on profile page, everythink works.

It might be silly as I'm using `nuxt-auth-utils` for the first time.

GitHub: https://github.com/TalentHubProject/monolith

(It's the `talent-hub_website` nuxtjs3 project)

Regards;

**Comment by Atinux** [comment]
Do you use `nuxt generate` for your website @Inerska ?

You need to use `nuxt build` and avoid any routeRules that can cache pages at the module require dynamic server-side rendering.

**Comment by Inerska** [comment]
> Do you use `nuxt generate` for your website @Inerska ?
> 
> You need to use `nuxt build` and avoid any routeRules that can cache pages at the module require dynamic server-side rendering.

Hello @Atinux, I am using the basic Vercel deployment configuration for NuxtJs.

![image](https://github.com/Atinux/nuxt-auth-utils/assets/50674490/16caf92a-b145-4307-9272-e34bba3fad45)

The repository is available at : 
https://github.com/TalentHubProject/monolith/tree/main/talent-hub_website

Regards;

**Comment by Inerska** [comment]
It was a routeRule that was prederendering pages, fixed. (cf. nuxt.config.[ts|js]).

Thanks!
