### ISSUE TITLE
Facebook Login

### ISSUE THREAD

**Issue by marcushohlbein** [Atinux/nuxt-auth-utils#61]
Hey,

are there plans to integrate facebook as a provider?

**Comment by Atinux** [comment]
Should be quite easy, PR is welcome :)

**Comment by adam-hudak** [comment]
Hi guys, I will take this task

**Comment by adam-hudak** [comment]
Hello @marcushohlbein, there is a new version [v0.0.24](https://github.com/Atinux/nuxt-auth-utils/blob/main/CHANGELOG.md#changelog) with Facebook provider out of the box. The implementation example is in the `playground` folder.

I hope it will make your life easier :)
