### ISSUE TITLE
Configure session expiration?

### ISSUE THREAD

**Issue by MrMarble** [Atinux/nuxt-auth-utils#73]
The cookie created with `setUserSession` is configured to expire with the browser session.
How do I persist the cookie for a longer time?

**Comment by Atinux** [comment]
Updated the readme to explain how to: https://github.com/Atinux/nuxt-auth-utils?tab=readme-ov-file#configuration

Basically like this:

```ts
export default defineNuxtConfig({
  modules: ['nuxt-auth-utils'],
  runtimeConfig: {
    session: {
      maxAge: 60 * 60 * 24 * 7 // 1 week
    }
  }
})
```
