### ISSUE TITLE
Impossible to login using Safari with localhost

### ISSUE THREAD

**Issue by vinceglb** [Atinux/nuxt-auth-utils#78]
I tried to use nuxt-auth-utils with Safari on macOS 14.4.1, but I've never been able to get it to work.

The cookie `nuxt-session` is never received on Safari, but it's working on Arc.

To reproduce:
- I use the playground from this repository or [nuxt-todos-edge](https://github.com/Atinux/nuxt-todos-edge)
- Put variables in the .env, I tried with Github and Auth0 providers: same results
- Use Safari, log in on the provider page like Github or Auth0
- The redirection works correctly to `http://localhost:3000/auth/auth0` for example
- The code in `auth0.get.ts` is executed without error. If I log `user` from the `onSuccess` event handler, I get the information like expected.
- But client side, I never get the `nuxt-session` cookie

But I can get https://todos.nuxt.dev/ works on Safari.

Is there anything I'm missing?

**Comment by raggesilver** [comment]
I was facing this issue today, @vinceglb. Safari is technically in the right here... The cookie set by this library uses `secure: true` (as it should), which means it only works on sites being served via HTTPS (not HTTP).

Following [these](https://nuxt.com/docs/api/nuxt-config#https) instructions will allow you to run Nuxt in dev mode served over HTTPS.

You can use the following commands to generate the certificates you need.

```bash
openssl genrsa 2048 > server.key
chmod 400 server.key
openssl req -new -x509 -nodes -sha256 -days 365 -key server.key -out server.crt
# https://stackoverflow.com/a/57895543/5609203
```

**Comment by vinceglb** [comment]
Good catch, Safari doesn't seem to accept secure cookies on localhost! Thank you 🙏

**Comment by Isypzenko** [comment]
Hi, can anybody help me, I've set certs into nuxt.config.ts

`server: {
    https: {
      key: "./certs/localhost+2-key.pem",
      cert: "./certs/localhost+2.pem",
    },
    port: 3000, // optional: specify the port
  },`
  but it doesn't work on Safari
