### ISSUE TITLE
204 No Content on Cloudflare Pages

### ISSUE THREAD

**Issue by ilrein** [Atinux/nuxt-auth-utils#80]
Hey folks, thanks for the awesome library. My github oauth login is working on localhost:3000 just fine.

But when I deploy to CF Pages, nothing seems to happen when I use `window.location.href = '/api/auth/github`

<img width="561" alt="Screen Shot 2024-04-13 at 12 53 23 PM" src="https://github.com/Atinux/nuxt-auth-utils/assets/5523014/a5737ebb-1816-4155-9262-03eb3a20baa4">

Cloudflare seems to be returning 204 no content, it's like I'm never hitting this route. I can see the github token has never been accessed. Any ideas? Seems like infrastructure configuration, but I can't figure it out.

I am not using `nuxt generate`, and my server API calls are working fine: https://minitinkertown.com/api/hello returns JSON

**Comment by Atinux** [comment]
Did you create the API route using `oauth.githubEventHandler`?

I recommend you to checkout `nuxt-todos-edge` as it is deployed on CF Pages too

**Comment by ilrein** [comment]
Yeah, I did. I tried both in `server/routes` and `server/api`

```
export default oauth.githubEventHandler({
  config: {
    emailRequired: true
  },
  async onSuccess(event, { user, tokens }) {
    await setUserSession(event, {
      user
    })
    return sendRedirect(event, '/dashboard')
  },
  // Optional, will return a json error and 401 status code by default
  onError(event, error) {
    console.error('GitHub OAuth error:', error)
    // return sendRedirect(event, '/')
  },
})
```

I am able to login on localhost. It's only when it's deployed that it doesn't work. I'm looking at the todo package but I cannot see anything obvious that stands out 🤔

**Comment by ilrein** [comment]
I may have gotten tokens mixed up 🤔 

Seems to be working! Thank you @Atinux (love nuxt)
