### ISSUE TITLE
[question] Working in a SPA

### ISSUE THREAD

**Issue by angelhdzmultimedia** [Atinux/nuxt-auth-utils#9]
Congratulations in the release of this awesome module. I have been waiting for it since I tried h3's sessions.

Question:   How to make this work in a SPA (`ssr: false` in `nuxt.config.ts`)? Thank you.

**Comment by sifferhans** [comment]
You cannot use this with SSR disabled for now, as it uses server routes.
https://github.com/Atinux/nuxt-auth-utils?tab=readme-ov-file#requirements
