### ISSUE TITLE
Github redirect uri not match. When i use https,how to deal with it?

### ISSUE THREAD

**Issue by LingBrian** [Atinux/nuxt-auth-utils#94]
This is my configs
![image](https://github.com/Atinux/nuxt-auth-utils/assets/43987995/86bf7029-1718-4c1f-9431-143adcc909fe)
Oh,it is so awful!
![image](https://github.com/Atinux/nuxt-auth-utils/assets/43987995/13ccbf5c-2659-4158-8931-7d6ade3bb473)

**Comment by Bryceed** [comment]
Same problem using Discord as provider
https://github.com/Atinux/nuxt-auth-utils/issues/81#issuecomment-2145146892

**Comment by LingBrian** [comment]
I failed to use it and there are few documents，so I prepare to develop my own oath2 application.😭😭😭😭

**Comment by raggesilver** [comment]
After thorough investigation (10 minutes playing with it), I found that something is downgrading the https request to http. Adding a log after [this line](https://github.com/Atinux/nuxt-auth-utils/blob/main/src/runtime/server/lib/oauth/github.ts#L87) will show us that the request the GitHub handler receives is flagged as http.

```ts
// getRequestURL(event) prints out:
{ href: 'http://localhost:3000/auth/github',
  origin: 'http://localhost:3000',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'localhost:3000',
  hostname: 'localhost',
  port: '3000',
  pathname: '/auth/github',
  search: '',
  searchParams: URLSearchParams {},
  hash: '' }
```

Since this package uses the `href` returned by `getRequestURL`, it's pretty obvious why GitHub rejects it.

Any thoughts @Atinux? Is this Vite/Nuxt dev server?

> PS: I made sure the navigation from UI to Nuxt Auth Utils' GitHub end-point was https. Tested on both Safari and Firefox on macOS.

**Comment by raggesilver** [comment]
> Is your project behind a proxy?
> 
> If so, it might be because we don't specify the `xForwardedProto` option 🤔
> 
> https://github.com/unjs/h3/blob/3249ca7ff5a430d59de6f9948478284dce395c97/src/utils/request.ts#L335

I haven't set up one manually.

This is my whole `nuxt.config.ts`:

```ts
export default defineNuxtConfig({
  devtools: { enabled: true, componentInspector: true },
  devServer: {
    https: true,
  },
  css: ["@unocss/reset/tailwind-compat.css", "~/assets/css/main.css"],
  modules: [
    "shadcn-nuxt",
    "@unocss/nuxt",
    "nuxt-auth-utils",
    "nuxt-icon",
    "@vueuse/nuxt",
    "@hebilicious/vue-query-nuxt",
  ],
  vueQuery: {
    queryClientOptions: {
      defaultOptions: {
        queries: {
          staleTime: 1000 * 60 * 5, // 5 minutes
        },
      },
    },
  },
});
```

Does `devServer: { https: true }` set up a proxy?

**Comment by LingBrian** [comment]
> Is your project behind a proxy?
> 
> If so, it might be because we don't specify the `xForwardedProto` option 🤔
> 
> https://github.com/unjs/h3/blob/3249ca7ff5a430d59de6f9948478284dce395c97/src/utils/request.ts#L335

Yes,I set a nginx proxy for this application port and  I bind it to my domain _dev.brl0.top_.

**Comment by lmiller1990** [comment]
Same issue for me -- I am using nignx to forward my port 80 traffic to Nuxt running on port 3000, and I notice the redirect_url is http, which is a mismatch. 🤔

**Comment by Atinux** [comment]
Similar to https://github.com/Atinux/nuxt-auth-utils/issues/117#issuecomment-2258052448

For such case where Nuxt cannot guess the protocol because it run behind a reverse proxy, use the `authorizationParams.redirect_uri` to overwrite it in production with your domain:

```ts
export default oauthProviderEventHandler({
  config: {
    authorizationParams: import.meta.dev
      ? {}
      : {
          redirect_uri: 'https://my-prod-website.com/auth/provider',
        },
  },
  async onSuccess(event, { user }) {
    // ...
  }
})
```

**Comment by SirMishaa** [comment]
Imo this shouldn't be closed. 

As @raggesilver points out in comments, he's not running under a proxy. 
I have the same problem.

It looks like more a bug than an expected behavior.
