### ISSUE TITLE
No session when fetching during SSR

### ISSUE THREAD

**Issue by raggesilver** [Atinux/nuxt-auth-utils#97]
I've noticed that `$fetch`ing during SSR results in a 401 when calling `getUserSession/requireUserSession` in the server.

GitHub setup:

```ts
import { AUTHORIZED_REDIRECT } from "~/lib/constants";
import { getOrCreateUser } from "~/server/services/user";

export default oauth.githubEventHandler({
  config: {
    emailRequired: true,
  },
  async onSuccess(event, { user: profile }) {
    const user = await getOrCreateUser("github", profile);
    await setUserSession(event, {
      user,
    });
    return sendRedirect(event, AUTHORIZED_REDIRECT);
  },
  // Optional, will return a json error and 401 status code by default
  onError(event, error) {
    console.error("GitHub OAuth error:", error, event);
    return sendRedirect(event, "/");
  },
});
```

API route setup:

```ts
import { getAllWorkspaces } from "~/server/services/workspace";

export default defineEventHandler(async (event) => {
  const session = await getUserSession(event);

  if (!session.user) {
    console.log("No user", JSON.stringify(event.node.req, null, 2));

    throw createError({ status: 401, message: "Unauthorized" });
  }

  return getAllWorkspaces(session.user.id);
});
```

Use in component:

```ts

const client = useQueryClient();
const { data, isLoading } = useQuery(
  {
    queryKey: ["workspaces"],
    queryFn: () =>
      $fetch("/api/workspace").catch((err) => {
        // Prints error in SSR
        console.error(err);
        throw err;
      }),
  },
  client,
);
```

No error is thrown in the client, and the data is fetched correctly. Erros on the server are only printed once (during SSR). Am I doing something wrong?

<details>
<summary>
Package versions
</summary>

```
nuxt-auth-utils@0.0.25
nuxt@3.11.2
nitropack@2.9.6
h3@1.11.1

node: v21.7.3
```

</details>

[Full repo](https://github.com/raggesilver/tasks.app).

**Comment by Atinux** [comment]
@raggesilver could you try with `useRequestFest()` instead?

See more context in https://github.com/nuxt/nuxt/issues/24813

**Comment by raggesilver** [comment]
That works! I take it from the issue you linked this is a bug in Nuxt, right? If not, it would be good to have this in the README.

Thanks

**Comment by Atinux** [comment]
It's not directly a bug but something we can improve in Nuxt for the long term.

Would you be happy to help me improve this readme to explain the usage of `useRequestFetch()` for this module?

**Comment by raggesilver** [comment]
For sure! I'll open a PR tomorrow.
